version: "3.1"

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    security_opt:
      - label:disable
    ports:
      - 80:80
      - 443:443
      - 8081:81

    volumes:
      - ${CONFIG_FOLDER}/data:/data
      - ${CONFIG_FOLDER}/letsencrypt:/etc/letsencrypt
    networks:
      reverseproxy-nw:
        ipv4_address: 172.22.0.69

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - lab-internal
      - reverseproxy-nw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  postgres:
    image: postgres
    container_name: posty
    restart: always
    shm_size: 1g
    ports:
      - 5432:5432
    networks:
      - lab-internal
      - reverseproxy-nw
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    networks:
      - lab-internal
      - reverseproxy-nw
    volumes:
      - /mnt/hdd/containers/lab/kuma:/app/data


networks:
  lab-internal:
  reverseproxy-nw:
    external: true
